src/StoreBundle/Entity/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: inisire
 * Date: 18.07.15
 * Time: 20:15
 */

namespace StoreBundle\Entity;

use CommonBundle\Entity\MetaData;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Embedded;
use Doctrine\ORM\Mapping\OneToMany;
use MediaBundle\Entity\Gallery;
use CategoryBundle\Entity\Category;
use CategoryBundle\Entity\Tag;
use CommonBundle\Entity\EnablableEntityTrait;
use CommonBundle\Entity\TimestampableEntityTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\Table;
use MediaBundle\Entity\Image;
use StoreBundle\Entity\ProductService;
use Tools\AliasGenerator;

/**
 * @Entity(repositoryClass="StoreBundle\Entity\Repository\ProductRepository")
 * @Table(name="products")
 * @HasLifecycleCallbacks()
 */
class Product
{
    use EnablableEntityTrait,
        TimestampableEntityTrait;

    /**
     * @var int
     * @Column(type="integer")
     * @Id()
     * @GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Column(type="string", length=128)
     */
    private $name;

    /**
     * @var string
     * @Column(type="string", length=128)
     */
    private $alias;

    /**
     * @var int
     * @Column(type="integer")
     */
    private $price;

    /**
     * @var Currency
     * @ManyToOne(targetEntity="StoreBundle\Entity\Currency")
     */
    private $currency;

    /**
     * @var ArrayCollection|Tag[]
     *
     * @ManyToMany(targetEntity="CategoryBundle\Entity\Tag", cascade={"persist"})
     */
    private $tags;

    /**
     * @var Gallery
     *
     * @ManyToOne(targetEntity="MediaBundle\Entity\Gallery", cascade={"persist"})
     */
    private $gallery;

    /**
     * @var ArrayCollection|Category[]
     *
     * @ManyToMany(targetEntity="CategoryBundle\Entity\Category", mappedBy="products")
     */
    private $categories;

    /**
     * @var ArrayCollection|ProductHasAttribute[]
     *
     * @OneToMany(targetEntity="StoreBundle\Entity\ProductHasAttribute", mappedBy="product", cascade={"persist"}, orphanRemoval=true)
     */
    private $attributes;

    /**
     * @var ArrayCollection|ProductService[]
     *
     * @OneToMany(targetEntity="StoreBundle\Entity\ProductService", mappedBy="product", cascade={"persist"}, orphanRemoval=true, indexBy="id")
     */
    private $services;

    /**
     * @var string
     *
     * @Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @var MetaData
     *
     * @Embedded(class="CommonBundle\Entity\MetaData")
     */
    private $meta;

    /**
     * @var int
     * @Column(type="integer", nullable=true)
     */
    private $popularity;

    /**
     * Initialize
     */
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->attributes = new ArrayCollection();
        $this->services = new ArrayCollection();
        $this->meta = new MetaData();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * @param string $alias
     *
     * @return $this
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return round($this->price / 100, 2);
    }

    /**
     * @return int
     */
    public function getPriceISO()
    {
        return $this->price;
    }

    /**
     * @param float $price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = round($price * 100);

        return $this;
    }

    /**
     * @return Currency
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @param Currency $currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * @return Tag[]|ArrayCollection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param Tag[]|ArrayCollection $tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->name ?: '';
    }

    /**
     * @PrePersist()
     * @PreUpdate()
     */
    public function generateAlias()
    {
        $this->alias = empty($this->alias)
            ? AliasGenerator::generate($this->name)
            : $this->alias;
    }

    /**
     * @return Gallery
     */
    public function getGallery()
    {
        return $this->gallery;
    }

    /**
     * @param Gallery $gallery
     *
     * @return $this
     */
    public function setGallery($gallery)
    {
        $this->gallery = $gallery;

        return $this;
    }

    /**
     * @return \CategoryBundle\Entity\Category[]|ArrayCollection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @return Image
     */
    public function getPreview()
    {
        if (!$this->gallery) {
            return null;
        }

        $images = $this->gallery->getImagesByFormat(Image::PRODUCT_PREVIEW);

        return $images->count() > 0 ? $images->first() : null;
    }

    /**
     * @return Image
     */
    public function getView()
    {
        if (!$this->gallery) {
            return null;
        }

        $images = $this->gallery->getImagesByFormat(Image::PRODUCT_SHOW);

        return $images->count() > 0 ? $images->first() : null;
    }

    /**
     * @return ArrayCollection|Image[]
     */
    public function getViews()
    {
        if (!$this->gallery) {
            return null;
        }

        return $this->gallery->getImagesByFormat(Image::PRODUCT_SHOW);
    }

    /**
     * @return ArrayCollection|ProductHasAttribute[]
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Add tag
     *
     * @param \CategoryBundle\Entity\Tag $tag
     *
     * @return Product
     */
    public function addTag(\CategoryBundle\Entity\Tag $tag)
    {
        $this->tags[] = $tag;

        return $this;
    }

    /**
     * Remove tag
     *
     * @param \CategoryBundle\Entity\Tag $tag
     */
    public function removeTag(\CategoryBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    /**
     * Add category
     *
     * @param \CategoryBundle\Entity\Category $category
     *
     * @return Product
     */
    public function addCategory(\CategoryBundle\Entity\Category $category)
    {
        $category->addProduct($this);
        $this->categories[] = $category;

        return $this;
    }

    /**
     * Remove category
     *
     * @param \CategoryBundle\Entity\Category $category
     */
    public function removeCategory(\CategoryBundle\Entity\Category $category)
    {
        $category->removeProduct($this);
        $this->categories->removeElement($category);
    }

    /**
     * Add attribute
     *
     * @param \StoreBundle\Entity\ProductHasAttribute $attribute
     *
     * @return Product
     */
    public function addAttribute(\StoreBundle\Entity\ProductHasAttribute $attribute)
    {
        $attribute->setProduct($this);
        $this->attributes[] = $attribute;

        return $this;
    }

    /**
     * Remove attribute
     *
     * @param \StoreBundle\Entity\ProductHasAttribute $attribute
     */
    public function removeAttribute(\StoreBundle\Entity\ProductHasAttribute $attribute)
    {
        $this->attributes->removeElement($attribute);
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Add service
     *
     * @param ProductService $service
     *
     * @return Product
     */
    public function addService(ProductService $service)
    {
        $service->setProduct($this);
        $this->services[] = $service;

        return $this;
    }

    /**
     * Remove service
     *
     * @param ProductService $service
     */
    public function removeService(ProductService $service)
    {
        $this->services->removeElement($service);
    }

    /**
     * Get services
     *
     * @return Collection
     */
    public function getServices()
    {
        return $this->services;
    }

src/StoreBundle/Controller/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: inisire
 * Date: 01.09.15
 * Time: 13:36
 */

namespace StoreBundle\Controller;

use StoreBundle\Form\Type\FilterFormType;
use StoreBundle\Model\Filter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends Controller
{
    /**
     * @param Request $request
     * @param         $alias
     *
     * @return Response
     */
    public function showAction(Request $request, $alias)
    {
        $doctrine = $this->get('doctrine');

        $categories = $doctrine->getRepository('CategoryBundle:Category')->findBy(['enabled' => true]);
        $product = $this->getDoctrine()->getRepository('StoreBundle:Product')->findOneBy([
            'alias'   => $alias,
            'enabled' => true,
        ]);

        if (!$product) {
            throw new NotFoundHttpException();
        }

        return $this->render('StoreBundle:Product:show.html.twig', ['product' => $product, 'categories' => $categories]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function listAction(Request $request)
    {
        $filter = new Filter();

//        if ($request->query->has('category')) {
//            $category = $this->getDoctrine()->getRepository('CategoryBundle:Category')->findOneBy([
//                'alias'   => $request->query->get('category'),
//                'enabled' => true,
//            ]);
//            if ($category) {
//                $filter->setCategory($category);
//            }
//        }

        $filterForm = $this->createForm(new FilterFormType(), $filter);
        $filterForm->handleRequest($request);
        if ($filterForm->isValid()) {
            $filter = $filterForm->getData();
        }

        $products = $this->getDoctrine()->getRepository('StoreBundle:Product')->findByFilter($filter);

        return $this->render('StoreBundle:Product:list.html.twig', [
            'title'       => 'Поиск',
            'description' => '',
            'products'    => $products,
            'filter'      => $filterForm->createView(),
        ]);
    }

    /**
     * @Route(path="/categories/{category}/products", name="category_products_list", methods={"GET"})
     *
     * @param Request $request
     * @param string  $category
     *
     * @return Response
     */
    public function listInCategoryAction(Request $request, $category)
    {
        $filter = new Filter();

        $category = $this->getDoctrine()->getRepository('CategoryBundle:Category')->findOneBy([
            'alias'   => $category,
            'enabled' => true,
        ]);

        if (!$category) {
            throw new NotFoundHttpException();
        }

        $filterForm = $this->createForm(new FilterFormType(), $filter);
        $filterForm->handleRequest($request);
        if ($filterForm->isValid()) {
            $filter = $filterForm->getData();
        }

        $products = $this->getDoctrine()->getRepository('StoreBundle:Product')->findByFilter($filter);

        return $this->render('StoreBundle:Product:list_category.html.twig', [
            'title'       => $category->getName(),
            'description' => '',
            'category'    => $category,
            'products'    => $products,
            'filter'      => $filterForm->createView(),
        ]);
    }
}

src/StoreBundle/Resources/views/Product/list.html.twig
{% extends "CommonBundle::base.html.twig" %}

{% form_theme filter _self %}

{%- block form_row -%}
    <div class="form-group">
        {{- form_label(form) -}}
        {{- form_errors(form) -}}
        {{- form_widget(form) -}}
    </div>
{%- endblock form_row -%}

{%- block choice_widget_collapsed -%}
    {%- if required and placeholder is none and not placeholder_in_choices and not multiple -%}
        {% set required = false %}
    {%- endif -%}
    <select class="form-control" {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {%- if placeholder is not none -%}
            <option value=""{% if required and value is empty %} selected="selected"{% endif %}>{{ placeholder != '' ? placeholder|trans({}, translation_domain) }}</option>
        {%- endif -%}
        {%- if preferred_choices|length > 0 -%}
            {% set options = preferred_choices %}
            {{- block('choice_widget_options') -}}
            {%- if choices|length > 0 and separator is not none -%}
                <option disabled="disabled">{{ separator }}</option>
            {%- endif -%}
        {%- endif -%}
        {%- set options = choices -%}
        {{- block('choice_widget_options') -}}
    </select>
{%- endblock choice_widget_collapsed -%}

{%- block button_widget -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
            '%name%': name,
            '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}
    <button class="btn btn-default" type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ label|trans({}, translation_domain) }}</button>
{%- endblock button_widget -%}

{%- block form_widget_simple -%}
    {%- set type = type|default('text') -%}
    <input class="form-control" type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{%- endblock form_widget_simple -%}

{% block breadcrumb %}
    <!-- page-intro start-->
    <div class="page-intro" style="margin-top: 0;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><i class="fa fa-home pr-10"></i><a href="/">Главная</a></li>
                        <li><a href="{{ path('categories_list') }}">Каталог</a></li>
                        <li class="active">Поиск</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- page-intro end -->
{% endblock %}

{% block content %}
    <!-- main-container start -->
    <!-- ================ -->
    <section class="main-container">
        <div class="container">
            <div class="row">
                {% include 'StoreBundle:Widget:product-3-column.html.twig' with {title: title, description: description, products: products} %}
                <aside class="col-md-3">
                    <div class="sidebar">
                        <div class="block clearfix">
                            <h2>Фильтр</h2>
                            <div class="separator"></div>
                            <div class="sorting-filters">
                                {{ form(filter) }}
                                {#<form>#}
                                {#<div class="form-group">#}
                                {#<label>Category</label>#}
                                {#<select class="form-control">#}
                                {#<option selected="selected">Smartphones</option>#}
                                {#<option>Tablets</option>#}
                                {#<option>Smart Watches</option>#}
                                {#<option>Desktops</option>#}
                                {#<option>Software</option>#}
                                {#<option>Accessories</option>#}
                                {#</select>#}
                                {#</div>#}
                                {#<div class="form-group">#}
                                {#<a href="/preview/idea/v.1.3/html/shop-listing-sidebar.html#" class="btn btn-default">Submit</a>#}
                                {#</div>#}
                                {#</form>#}
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </section>
{% endblock %}

src/StoreBundle/Resources/views/Product/list_category.html.twig
{% extends "CommonBundle::base.html.twig" %}

{% block title %}{{ category.meta.title }}{% endblock %}
{% block description %}{{ category.meta.description }}{% endblock %}
{% block keywords %}{{ category.meta.keywords }}{% endblock %}

{% form_theme filter _self %}

{%- block form_row -%}
    <div class="form-group">
        {{- form_label(form) -}}
        {{- form_errors(form) -}}
        {{- form_widget(form) -}}
    </div>
{%- endblock form_row -%}

{%- block choice_widget_collapsed -%}
    {%- if required and placeholder is none and not placeholder_in_choices and not multiple -%}
        {% set required = false %}
    {%- endif -%}
    <select class="form-control" {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {%- if placeholder is not none -%}
            <option value=""{% if required and value is empty %} selected="selected"{% endif %}>{{ placeholder != '' ? placeholder|trans({}, translation_domain) }}</option>
        {%- endif -%}
        {%- if preferred_choices|length > 0 -%}
            {% set options = preferred_choices %}
            {{- block('choice_widget_options') -}}
            {%- if choices|length > 0 and separator is not none -%}
                <option disabled="disabled">{{ separator }}</option>
            {%- endif -%}
        {%- endif -%}
        {%- set options = choices -%}
        {{- block('choice_widget_options') -}}
    </select>
{%- endblock choice_widget_collapsed -%}

{%- block button_widget -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
            '%name%': name,
            '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}
    <button class="btn btn-default" type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ label|trans({}, translation_domain) }}</button>
{%- endblock button_widget -%}

{%- block form_widget_simple -%}
    {%- set type = type|default('text') -%}
    <input class="form-control" type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{%- endblock form_widget_simple -%}

{% block breadcrumb %}
    <!-- page-intro start-->
    <div class="page-intro" style="margin-top: 0;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><i class="fa fa-home pr-10"></i><a href="/">Главная</a></li>
                        <li><a href="{{ path('categories_list') }}">Каталог</a></li>
                        <li class="active">{{ category.name }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- page-intro end -->
{% endblock %}

{% block content %}
    <!-- main-container start -->
    <!-- ================ -->
    <section class="main-container">
        <div class="container">
            <div class="row">
                {% include 'StoreBundle:Widget:product-3-column.html.twig' with {title: category.name, description: category.description, products: products} %}
                <aside class="col-md-3">
                    <div class="sidebar">
                        <div class="block clearfix">
                            <h2>Фильтр</h2>
                            <div class="separator"></div>
                            <div class="sorting-filters">
                                {{ form(filter) }}
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>

        {% if category.article %}
            <div class="container">
                <div class="row">
                    <div class="main col-md-12">

                        <h2>{{ category.article.title | raw }}</h2>
                        <div class="separator-2"></div>

                        {{ category.article.content | raw }}

                    </div>
                </div>
            </div>
        {% endif %}
    </section>
{% endblock %}

src/StoreBundle/Resources/views/Product/show.html.twig
{% extends 'CommonBundle::base.html.twig' %}

{% block title %}{{ product.meta.title }}{% endblock %}
{% block description %}{{ product.meta.description }}{% endblock %}
{% block keywords %}{{ product.meta.keywords }}{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12">

            {% include 'CategoryBundle:Widget:categories.html.twig' %}

            </div>

            <div class="clearfix visible-sm"></div>

            <!-- Product Detail -->
            <div class="col-lg-9 col-md-9 col-sm-12">
                <div class="col-lg-12 col-sm-12">
                    <span class="title">{{ product.name }}</span>
                </div>
                <div class="col-lg-12 col-sm-12 hero-feature">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <!-- Main Image -->
                            <div class="product-main-image-container">
                                <img src="{{ asset('/images/loader.gif') }}" alt="" class="product-loader" style="display: none;">
								<span class="thumbnail product-main-image" style="position: relative; overflow: hidden;">
									<img src="{{ asset(product.view) }}" alt="{{ asset(view.alt) }}">
								<img src="{{ asset(product.view) }}" class="zoomImg" style="position: absolute; top: -3.19797px; left: -1.3401px; opacity: 0; width: 400px; height: 400px; border: none; max-width: none; max-height: none;"></span>
                            </div>
                            <!-- End Main Image -->

                            <!-- Thumbnail Image -->
                            {% for view in product.views %}
                                <div class="col-xs-3 product-thumb-image">
                                    <a href="{{ asset(view) }}" class="thumbnail">
                                        <img src="{{ asset(view) }}" alt="{{ asset(view.alt) }}">
                                    </a>
                                </div>
                            {% endfor %}
                            <!-- End Thumbnail Image -->
                        </div>

                        <div class="visible-xs">
                            <div class="clearfix"></div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="well product-short-detail">
                                <div class="row">
                                    <form role="form" id="order">
                                        <input type="hidden" name="product" value="{{ product.id }}">
                                        <div class="the-list">
                                            <h3 class="col-xs-12" id="product-price" class="price">
                                                <!-- <span class="price-old">$169</span> -->
                                                {{ product.price }} <span>{{ product.currency }}</span>
                                            </h3>
                                        </div>
                                        <div class="the-list">
                                            <div class="col-xs-4">В наличии:</div>
                                            <div class="col-xs-8">
                                                <!-- <span class="red">OUT OF STOCK</span> -->
                                                <span class="green">Да</span>
                                            </div>
                                        </div>

                                        <div class="clearfix"></div>
                                        <hr>
                                        <hr/>

                                        <div class="col-xs-12 input-qty-detail">
                                            <input type="text" name="quantity" class="form-control input-qty text-center" value="1">
                                            <button type="submit" class="btn btn-default pull-left"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
                                        </div>
                                    </form>

                                    <div class="clearfix"></div><br>
                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div><br clear="all">
                            <div class="col-xs-12 product-detail-tab">
                                {{ product.description|raw }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
        </div>
        <!-- End Product Detail -->
    </div>
{% endblock %}